// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCh-xhjevs2IH7TbMRzd1Sdej9GAF4-bIw',
    appId: '1:903720069953:ios:b40d71d05ba1f8e6a28fc0',
    messagingSenderId: '903720069953',
    projectId: 'fir-f1273',
    storageBucket: 'fir-f1273.firebasestorage.app',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCh-xhjevs2IH7TbMRzd1Sdej9GAF4-bIw',
    appId: '1:903720069953:ios:b40d71d05ba1f8e6a28fc0',
    messagingSenderId: '903720069953',
    projectId: 'fir-f1273',
    storageBucket: 'fir-f1273.firebasestorage.app',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDp4J_HbyV9srWYsOuJYaqJwlOa53BkNGE',
    appId: '1:903720069953:web:eff6b248215d9c9fa28fc0',
    messagingSenderId: '903720069953',
    projectId: 'fir-f1273',
    authDomain: 'fir-f1273.firebaseapp.com',
    storageBucket: 'fir-f1273.firebasestorage.app',
    measurementId: 'G-TZBQBTWL1V',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDp4J_HbyV9srWYsOuJYaqJwlOa53BkNGE',
    appId: '1:903720069953:web:eff6b248215d9c9fa28fc0',
    messagingSenderId: '903720069953',
    projectId: 'fir-f1273',
    authDomain: 'fir-f1273.firebaseapp.com',
    storageBucket: 'fir-f1273.firebasestorage.app',
    measurementId: 'G-TZBQBTWL1V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuxJ4rD_ljMbw6r-quxlwPaFUBlWAOn58',
    appId: '1:903720069953:android:5123ca6a8e8ff7dba28fc0',
    messagingSenderId: '903720069953',
    projectId: 'fir-f1273',
    storageBucket: 'fir-f1273.firebasestorage.app',
  );

}